import { ChefHat, Gift, Calendar, Package, Bitcoin, Key, FileText } from "lucide-react"
import { ConverterMetadata } from "@/types/converter"

export const helpfulCalculators: ConverterMetadata[] = [
  {
    id: "recipe-scaler",
    title: "Recipe Scaler",
    description: "Scale recipe ingredients for different serving sizes",
    category: "helpful",
    icon: ChefHat,
    href: "/helpful-calculators/recipe-scaler",
    keywords: ["recipe", "scale", "ingredients", "cooking", "servings", "portions"],
    popular: true,
  },
  {
    id: "secret-santa",
    title: "Secret Santa Generator",
    description: "Organize gift exchanges with automatic pairing",
    category: "helpful",
    icon: Gift,
    href: "/helpful-calculators/secret-santa",
    keywords: ["secret santa", "gift exchange", "christmas", "holiday", "random", "generator"],
    popular: true,
  },
  {
    id: "holiday-countdown",
    title: "Holiday Countdown",
    description: "Count down to holidays and special events",
    category: "helpful",
    icon: Calendar,
    href: "/helpful-calculators/holiday-countdown",
    keywords: ["countdown", "holiday", "christmas", "new year", "birthday", "event", "timer"],
    popular: true,
  },
  // Shipping Cost Calculator - Temporarily disabled (USPS API unavailable)
  // Uncomment when USPS API access is available:
  // {
  //   id: "shipping-cost-calculator",
  //   title: "Shipping Cost Calculator",
  //   description: "Compare shipping rates from USPS, UPS, FedEx, and DHL",
  //   category: "helpful",
  //   icon: Package,
  //   href: "/helpful-calculators/shipping-cost",
  //   keywords: ["shipping", "cost", "usps", "ups", "fedex", "dhl", "delivery", "package", "mail", "holiday"],
  //   popular: true,
  // },
  {
    id: "crypto-converter",
    title: "Crypto Currency Converter",
    description: "Convert cryptocurrencies to fiat currencies with live rates",
    category: "helpful",
    icon: Bitcoin,
    href: "/helpful-calculators/crypto-converter",
    keywords: ["crypto", "cryptocurrency", "bitcoin", "ethereum", "convert", "price", "market", "trading"],
    popular: true,
  },
  {
    id: "password-generator",
    title: "Password Generator",
    description: "Generate strong, secure passwords with customizable options",
    category: "helpful",
    icon: Key,
    href: "/helpful-calculators/password-generator",
    keywords: ["password", "generator", "security", "random", "strong", "secure"],
    popular: true,
  },
  {
    id: "cheatsheet-builder",
    title: "Cheatsheet Builder",
    description: "Create custom cheatsheets with LaTeX support and export to PDF",
    category: "helpful",
    icon: FileText,
    href: "/helpful-calculators/cheatsheet-builder",
    keywords: ["cheatsheet", "study guide", "latex", "formula", "pdf", "exam", "notes", "reference"],
    popular: true,
  },
]