import { Calculator, Heart, DollarSign, Percent, TrendingUp, LineChart, Calendar, Utensils, Dumbbell, Baby, Paintbrush, Home, Truck } from "lucide-react"
import { ConverterMetadata } from "@/types/converter"

/**
 * Calculators Registry
 * All calculator tools are registered here
 */
export const calculatorTools: ConverterMetadata[] = [
  {
    id: "graphing-calculator",
    title: "Graphing Calculator",
    description: "Plot mathematical functions with symbolic expressions",
    category: "calculator",
    icon: LineChart,
    href: "/calculators/graphing",
    keywords: ["graphing", "calculator", "plot", "function", "graph", "symbolic", "math"],
    popular: true,
  },
  {
    id: "scientific-calculator",
    title: "Scientific Calculator",
    description: "Advanced calculator with scientific functions",
    category: "calculator",
    icon: Calculator,
    href: "/calculators/scientific",
    keywords: ["scientific", "calculator", "math", "trigonometry", "logarithm", "advanced"],
    popular: true,
  },
  {
    id: "bmi-calculator",
    title: "BMI Calculator",
    description: "Calculate your Body Mass Index",
    category: "calculator",
    icon: Heart,
    href: "/calculators/bmi",
    keywords: ["bmi", "body mass index", "health", "weight", "fitness"],
    popular: true,
  },
  {
    id: "loan-mortgage-calculator",
    title: "Interest, Loan and Mortgage Calculator",
    description: "Calculate interest rates, loan payments, mortgages, and total interest",
    category: "calculator",
    icon: DollarSign,
    href: "/calculators/loan",
    keywords: ["interest", "loan", "mortgage", "payment", "finance", "debt", "home", "rate"],
    popular: true,
  },
  {
    id: "tip-calculator",
    title: "Tip Calculator",
    description: "Calculate tips and split bills",
    category: "calculator",
    icon: Percent,
    href: "/calculators/tip",
    keywords: ["tip", "gratuity", "restaurant", "bill", "split"],
    popular: true,
  },
  {
    id: "percentage-calculator",
    title: "Percentage Calculator",
    description: "Calculate percentages, increases, and decreases",
    category: "calculator",
    icon: Percent,
    href: "/calculators/percentage",
    keywords: ["percentage", "percent", "increase", "decrease", "discount"],
    popular: false,
  },
  {
    id: "date-calculator",
    title: "Date Calculator",
    description: "Add days to dates and calculate date differences",
    category: "calculator",
    icon: Calendar,
    href: "/calculators/date-calculator",
    keywords: ["date", "calendar", "days", "difference", "add", "subtract", "time"],
    popular: true,
  },
  {
    id: "calorie-calculator",
    title: "Calorie Calculator",
    description: "Calculate daily calorie needs based on age, gender, and activity level",
    category: "calculator",
    icon: Utensils,
    href: "/calculators/calorie",
    keywords: ["calorie", "nutrition", "diet", "health", "fitness", "daily", "needs"],
    popular: false,
  },
  {
    id: "protein-calculator",
    title: "Protein Calculator",
    description: "Calculate daily protein needs based on weight and activity level",
    category: "calculator",
    icon: Dumbbell,
    href: "/calculators/protein",
    keywords: ["protein", "nutrition", "fitness", "muscle", "diet", "daily", "needs"],
    popular: false,
  },
  {
    id: "pregnancy-calculator",
    title: "Pregnancy Due Date Calculator",
    description: "Calculate due date and weeks pregnant from last period",
    category: "calculator",
    icon: Baby,
    href: "/calculators/pregnancy",
    keywords: ["pregnancy", "due date", "baby", "weeks", "pregnant", "maternity"],
    popular: false,
  },
  {
    id: "paint-calculator",
    title: "Paint Calculator",
    description: "Calculate gallons of paint needed for room dimensions",
    category: "calculator",
    icon: Paintbrush,
    href: "/calculators/paint",
    keywords: ["paint", "room", "wall", "coverage", "gallons", "home", "improvement"],
    popular: false,
  },
  {
    id: "flooring-calculator",
    title: "Flooring Calculator",
    description: "Calculate square footage and materials needed for flooring",
    category: "calculator",
    icon: Home,
    href: "/calculators/flooring",
    keywords: ["flooring", "square feet", "materials", "home", "renovation", "carpet"],
    popular: false,
  },
  {
    id: "concrete-calculator",
    title: "Concrete Calculator",
    description: "Calculate cubic yards of concrete needed for projects",
    category: "calculator",
    icon: Truck,
    href: "/calculators/concrete",
    keywords: ["concrete", "cubic yards", "construction", "driveway", "foundation"],
    popular: false,
  },
]
