import { Sliders, ImageIcon, Music, FileCode, Wand2, Palette } from "lucide-react"
import { ConverterMetadata } from "@/types/converter"

/**
 * Filters Registry
 * All filter tools from FILTER_SERVICE_SPEC.md (image, audio, and data filters)
 */
export const filterTools: ConverterMetadata[] = [
  // Image Filters - Basic Adjustments
  {
    id: "image-brightness",
    title: "Adjust Brightness",
    description: "Adjust image brightness levels",
    category: "image-filter",
    icon: Sliders,
    href: "/filters/image-brightness",
    keywords: ["brightness", "image", "adjust", "light", "dark"],
    popular: true,
  },
  {
    id: "image-contrast",
    title: "Adjust Contrast",
    description: "Adjust image contrast levels",
    category: "image-filter",
    icon: Sliders,
    href: "/filters/image-contrast",
    keywords: ["contrast", "image", "adjust"],
    popular: true,
  },
  {
    id: "image-saturation",
    title: "Adjust Saturation",
    description: "Adjust color saturation in images",
    category: "image-filter",
    icon: Palette,
    href: "/filters/image-saturation",
    keywords: ["saturation", "image", "color", "vibrance"],
    popular: true,
  },

  // Image Filters - Color Effects
  {
    id: "image-grayscale",
    title: "Grayscale Filter",
    description: "Convert images to black and white",
    category: "image-filter",
    icon: ImageIcon,
    href: "/filters/image-grayscale",
    keywords: ["grayscale", "black white", "image", "filter"],
    popular: true,
  },
  {
    id: "image-sepia",
    title: "Sepia Filter",
    description: "Apply vintage sepia tone effect",
    category: "image-filter",
    icon: Wand2,
    href: "/filters/image-sepia",
    keywords: ["sepia", "vintage", "image", "filter", "retro"],
    popular: true,
  },
  {
    id: "image-vintage",
    title: "Vintage Filter",
    description: "Apply vintage photo effect",
    category: "image-filter",
    icon: Wand2,
    href: "/filters/image-vintage",
    keywords: ["vintage", "retro", "image", "filter", "old"],
    popular: true,
  },

  // Image Filters - Enhancement
  {
    id: "image-blur",
    title: "Blur Image",
    description: "Apply blur effect to images",
    category: "image-filter",
    icon: Sliders,
    href: "/filters/image-blur",
    keywords: ["blur", "image", "soften", "gaussian"],
    popular: true,
  },
  {
    id: "image-sharpen",
    title: "Sharpen Image",
    description: "Enhance image sharpness and details",
    category: "image-filter",
    icon: Sliders,
    href: "/filters/image-sharpen",
    keywords: ["sharpen", "image", "enhance", "details", "clarity"],
    popular: true,
  },

  // Instagram-style Filters
  {
    id: "filter-valencia",
    title: "Valencia Filter",
    description: "Instagram Valencia filter effect",
    category: "image-filter",
    icon: Wand2,
    href: "/filters/valencia",
    keywords: ["valencia", "instagram", "filter", "warm"],
    popular: true,
  },
  {
    id: "filter-nashville",
    title: "Nashville Filter",
    description: "Instagram Nashville filter effect",
    category: "image-filter",
    icon: Wand2,
    href: "/filters/nashville",
    keywords: ["nashville", "instagram", "filter", "warm", "vintage"],
    popular: true,
  },
  {
    id: "filter-xpro2",
    title: "X-Pro II Filter",
    description: "Instagram X-Pro II filter effect",
    category: "image-filter",
    icon: Wand2,
    href: "/filters/xpro2",
    keywords: ["xpro", "instagram", "filter", "dramatic"],
    popular: false,
  },

  // Audio Filters
  {
    id: "audio-equalizer",
    title: "Audio Equalizer",
    description: "Adjust audio frequencies with EQ",
    category: "audio-filter",
    icon: Sliders,
    href: "/filters/audio-equalizer",
    keywords: ["equalizer", "audio", "eq", "bass", "treble"],
    popular: true,
  },
  {
    id: "audio-reverb",
    title: "Reverb Effect",
    description: "Add reverb to audio files",
    category: "audio-filter",
    icon: Music,
    href: "/filters/audio-reverb",
    keywords: ["reverb", "audio", "echo", "effect", "space"],
    popular: true,
  },
  {
    id: "audio-echo",
    title: "Echo Effect",
    description: "Add echo effect to audio",
    category: "audio-filter",
    icon: Music,
    href: "/filters/audio-echo",
    keywords: ["echo", "audio", "delay", "effect"],
    popular: false,
  },
  {
    id: "audio-noise-reduction",
    title: "Noise Reduction",
    description: "Remove background noise from audio",
    category: "audio-filter",
    icon: Music,
    href: "/filters/audio-noise-reduction",
    keywords: ["noise", "reduction", "audio", "clean", "denoise"],
    popular: true,
  },
  {
    id: "audio-normalize",
    title: "Normalize Audio",
    description: "Normalize audio volume levels",
    category: "audio-filter",
    icon: Sliders,
    href: "/filters/audio-normalize",
    keywords: ["normalize", "audio", "volume", "level"],
    popular: true,
  },
  {
    id: "audio-bass-boost",
    title: "Bass Boost",
    description: "Enhance bass frequencies in audio",
    category: "audio-filter",
    icon: Music,
    href: "/filters/audio-bass-boost",
    keywords: ["bass", "boost", "audio", "low frequency", "enhance"],
    popular: true,
  },

  // Data Filters
  {
    id: "json-format",
    title: "Format JSON",
    description: "Format and prettify JSON data",
    category: "data-filter",
    icon: FileCode,
    href: "/filters/json-format",
    keywords: ["json", "format", "prettify", "beautify"],
    popular: true,
  },
  {
    id: "json-minify",
    title: "Minify JSON",
    description: "Compress JSON by removing whitespace",
    category: "data-filter",
    icon: FileCode,
    href: "/filters/json-minify",
    keywords: ["json", "minify", "compress", "compact"],
    popular: true,
  },
  {
    id: "xml-format",
    title: "Format XML",
    description: "Format and prettify XML data",
    category: "data-filter",
    icon: FileCode,
    href: "/filters/xml-format",
    keywords: ["xml", "format", "prettify", "beautify"],
    popular: false,
  },
  {
    id: "csv-clean",
    title: "Clean CSV",
    description: "Clean and format CSV data",
    category: "data-filter",
    icon: FileCode,
    href: "/filters/csv-clean",
    keywords: ["csv", "clean", "format", "data"],
    popular: true,
  },
  {
    id: "text-case",
    title: "Text Case Converter",
    description: "Convert text between different cases",
    category: "data-filter",
    icon: FileCode,
    href: "/filters/text-case",
    keywords: ["text", "case", "upper", "lower", "camel", "snake"],
    popular: true,
  },
  {
    id: "extract-emails",
    title: "Extract Emails",
    description: "Extract email addresses from text",
    category: "data-filter",
    icon: FileCode,
    href: "/filters/extract-emails",
    keywords: ["extract", "email", "text", "find", "parse"],
    popular: true,
  },
  {
    id: "extract-urls",
    title: "Extract URLs",
    description: "Extract URLs from text",
    category: "data-filter",
    icon: FileCode,
    href: "/filters/extract-urls",
    keywords: ["extract", "url", "text", "find", "parse", "links"],
    popular: true,
  },
]
