import {
  Cloud,
  Shield,
  Route,
  FileText,
  Truck,
  DollarSign,
  Weight,
  Droplets,
  Gauge,
  Clock,
  ListChecks,
  Wallet,
} from "lucide-react"
import { ConverterMetadata } from "@/types/converter"

/**
 * Adventure Registry
 * Tools for travelers, bikers, campers, backpackers, and motorcyclists.
 */
export const adventureTools: ConverterMetadata[] = [
  {
    id: "weather-window-risk-score",
    title: "Weather Window Risk Score",
    description: "Estimate trip weather risk for your selected window",
    category: "adventure",
    icon: Cloud,
    href: "/adventure/weather-window-risk-score",
    keywords: ["weather", "risk", "trip", "forecast", "planning"],
    popular: true,
  },
  {
    id: "emergency-info-card-generator",
    title: "Emergency Info Card Generator",
    description: "Generate a printable emergency contact card",
    category: "adventure",
    icon: Shield,
    href: "/adventure/emergency-info-card-generator",
    keywords: ["emergency", "contact", "medical", "card", "safety"],
    popular: true,
  },
  {
    id: "route-time-cost-fuel-planner",
    title: "Route Time, Cost & Fuel Planner",
    description: "Plan route duration, fuel needs, and trip cost",
    category: "adventure",
    icon: Route,
    href: "/adventure/route-time-cost-fuel-planner",
    keywords: ["route", "eta", "fuel", "cost", "trip planner"],
    popular: true,
  },
  {
    id: "offline-packing-checklist-exporter",
    title: "Offline Packing Checklist Exporter",
    description: "Build, save, and export packing checklists",
    category: "adventure",
    icon: FileText,
    href: "/adventure/offline-packing-checklist-exporter",
    keywords: ["packing", "checklist", "offline", "travel", "export"],
    popular: true,
  },
  {
    id: "ride-range-fuel-stop-planner",
    title: "Ride Range & Fuel Stop Planner",
    description: "Estimate safe range and fuel stop intervals",
    category: "adventure",
    icon: Truck,
    href: "/adventure/ride-range-fuel-stop-planner",
    keywords: ["motorcycle", "fuel", "range", "stops", "ride"],
    popular: true,
  },
  {
    id: "trip-budget-currency-buffer-planner",
    title: "Trip Budget & Currency Buffer Planner",
    description: "Plan trip budget with an exchange-rate safety buffer",
    category: "adventure",
    icon: DollarSign,
    href: "/adventure/trip-budget-currency-buffer-planner",
    keywords: ["travel budget", "currency", "buffer", "trip cost"],
    popular: true,
  },
  {
    id: "base-weight-optimizer",
    title: "Base Weight Optimizer",
    description: "Analyze pack weight and identify heavy items",
    category: "adventure",
    icon: Weight,
    href: "/adventure/base-weight-optimizer",
    keywords: ["backpacking", "base weight", "pack", "gear"],
    popular: true,
  },
  {
    id: "water-food-planner",
    title: "Water & Food Planner",
    description: "Estimate daily water and food needs for the trip",
    category: "adventure",
    icon: Droplets,
    href: "/adventure/water-food-planner",
    keywords: ["camping", "water", "food", "ration", "planner"],
    popular: true,
  },
  {
    id: "ride-fueling-calculator",
    title: "Ride Fueling Calculator",
    description: "Estimate carb, fluid, and electrolyte targets",
    category: "adventure",
    icon: Gauge,
    href: "/adventure/ride-fueling-calculator",
    keywords: ["cycling", "fueling", "carbs", "hydration", "ride"],
    popular: true,
  },
  {
    id: "pace-eta-planner",
    title: "Pace & ETA Planner",
    description: "Estimate moving time and total ETA including breaks",
    category: "adventure",
    icon: Clock,
    href: "/adventure/pace-eta-planner",
    keywords: ["pace", "eta", "hike", "ride", "timing"],
    popular: true,
  },
  {
    id: "smart-packing-list-builder",
    title: "Smart Packing List Builder",
    description: "Generate a tailored packing list by trip conditions",
    category: "adventure",
    icon: ListChecks,
    href: "/adventure/smart-packing-list-builder",
    keywords: ["packing", "travel", "weather", "gear", "checklist"],
    popular: true,
  },
  {
    id: "trip-cost-estimator",
    title: "Trip Cost Estimator",
    description: "Estimate daily and total trip costs",
    category: "adventure",
    icon: Wallet,
    href: "/adventure/trip-cost-estimator",
    keywords: ["trip", "cost", "budget", "travel", "estimate"],
    popular: true,
  },
]
