import { Thermometer, Ruler, Weight, Droplet, Clock, Gauge, Square, Zap, Orbit, Gauge as Pressure, HardDrive, FileJson, Calendar } from "lucide-react"
import { ConverterMetadata } from "@/types/converter"

/**
 * Unit Conversions Registry
 * Consolidated converters for major unit categories
 */
export const unitConversionTools: ConverterMetadata[] = [
  {
    id: "length",
    title: "Length Converter",
    description: "Convert between microns, millimeters, inches, feet, meters, kilometers, miles",
    category: "distance",
    icon: Ruler,
    href: "/unit-conversions/length",
    keywords: ["length", "distance", "inches", "centimeters", "feet", "meters", "miles", "kilometers", "micron"],
    popular: true,
  },
  {
    id: "mass",
    title: "Mass & Weight Converter",
    description: "Convert between micrograms, grams, ounces, pounds, kilograms, tons",
    category: "weight",
    icon: Weight,
    href: "/unit-conversions/mass",
    keywords: ["mass", "weight", "grams", "ounces", "pounds", "kilograms", "tons", "microgram"],
    popular: true,
  },
  {
    id: "temperature",
    title: "Temperature Converter",
    description: "Convert between Celsius, Fahrenheit, Kelvin, and Rankine",
    category: "temperature",
    icon: Thermometer,
    href: "/unit-conversions/temperature",
    keywords: ["temperature", "celsius", "fahrenheit", "kelvin", "rankine", "degrees"],
    popular: true,
  },
  {
    id: "volume",
    title: "Volume Converter",
    description: "Convert between milliliters, cups, pints, liters, gallons, cubic meters",
    category: "volume",
    icon: Droplet,
    href: "/unit-conversions/volume",
    keywords: ["volume", "liquid", "milliliters", "liters", "gallons", "cups", "pints", "fluid ounces"],
    popular: true,
  },
  {
    id: "date-time",
    title: "Date-Time Calculator",
    description: "Calculate dates, add durations, and find time between dates with calendar views",
    category: "time",
    icon: Calendar,
    href: "/unit-conversions/date-time",
    keywords: ["date", "calendar", "day of week", "date difference", "add days", "date calculator", "time between dates"],
    popular: true,
  },
  {
    id: "time",
    title: "Time Converter",
    description: "Convert between nanoseconds, seconds, minutes, hours, days, years",
    category: "time",
    icon: Clock,
    href: "/unit-conversions/time",
    keywords: ["time", "duration", "seconds", "minutes", "hours", "days", "weeks", "months", "years"],
    popular: false,
  },
  {
    id: "speed",
    title: "Speed Converter",
    description: "Convert between mph, km/h, m/s, knots, Mach, speed of light",
    category: "speed",
    icon: Gauge,
    href: "/unit-conversions/speed",
    keywords: ["speed", "velocity", "mph", "kmh", "knots", "mach", "meters per second"],
    popular: false,
  },
  {
    id: "area",
    title: "Area Converter",
    description: "Convert between square feet, square meters, acres, hectares",
    category: "area",
    icon: Square,
    href: "/unit-conversions/area",
    keywords: ["area", "surface", "square feet", "square meters", "acres", "hectares", "land"],
    popular: false,
  },
  {
    id: "energy",
    title: "Energy Converter",
    description: "Convert between joules, calories, BTU, kWh, electron volts",
    category: "energy",
    icon: Zap,
    href: "/unit-conversions/energy",
    keywords: ["energy", "joules", "calories", "btu", "kwh", "electron volt", "watt hour"],
    popular: false,
  },
  {
    id: "pressure",
    title: "Pressure Converter",
    description: "Convert between PSI, Bar, Pascal, and other pressure units",
    category: "pressure",
    icon: Pressure,
    href: "/unit-conversions/pressure",
    keywords: ["pressure", "psi", "bar", "pascal", "atmosphere", "torr"],
    popular: false,
  },
  {
    id: "data",
    title: "Data Size Converter",
    description: "Convert between KB, MB, GB, TB, and other data units",
    category: "data",
    icon: HardDrive,
    href: "/unit-conversions/data",
    keywords: ["data", "storage", "kb", "mb", "gb", "tb", "bytes", "bits"],
    popular: false,
  },
  {
    id: "data-format-converter",
    title: "Data Format Converter",
    description: "Convert between JSON, XML, YAML, and CSV data formats",
    category: "data",
    icon: FileJson,
    href: "/file-converters/data",
    keywords: ["json", "xml", "yaml", "csv", "data", "api"],
    popular: true,
  },
  {
    id: "spacetime",
    title: "Spacetime Converter (Lorentz Transformation)",
    description: "Convert relativistic space-time coordinates using Lorentz transformations",
    category: "spacetime",
    icon: Orbit,
    href: "/unit-conversions/spacetime",
    keywords: ["spacetime", "lorentz", "relativity", "physics", "transformation", "einstein", "light years", "parsecs"],
    popular: false,
  },
]
