import { Image as ImageIcon, Video, Music, FileAudio, Film } from "lucide-react"
import { ConverterMetadata } from "@/types/converter"

/**
 * Media Converters Registry
 * All media conversion tools from MEDIA_CONVERSION_SERVICE_SPEC.md
 */
export const mediaConverterTools: ConverterMetadata[] = [
  // Video Format Conversions
  {
    id: "mp4-avi",
    title: "MP4 to AVI",
    description: "Convert MP4 videos to AVI format",
    category: "video",
    icon: Video,
    href: "/media-converters/mp4-avi",
    keywords: ["mp4", "avi", "video", "convert"],
    popular: true,
  },
  {
    id: "avi-mp4",
    title: "AVI to MP4",
    description: "Convert AVI videos to MP4 format",
    category: "video",
    icon: Video,
    href: "/media-converters/avi-mp4",
    keywords: ["avi", "mp4", "video", "convert"],
    popular: false,
  },
  {
    id: "mp4-mov",
    title: "MP4 to MOV",
    description: "Convert MP4 videos to MOV (QuickTime) format",
    category: "video",
    icon: Video,
    href: "/media-converters/mp4-mov",
    keywords: ["mp4", "mov", "quicktime", "video"],
    popular: false,
  },
  {
    id: "mov-mp4",
    title: "MOV to MP4",
    description: "Convert MOV (QuickTime) videos to MP4",
    category: "video",
    icon: Video,
    href: "/media-converters/mov-mp4",
    keywords: ["mov", "mp4", "quicktime", "video"],
    popular: false,
  },
  {
    id: "mp4-webm",
    title: "MP4 to WebM",
    description: "Convert MP4 videos to WebM format",
    category: "video",
    icon: Video,
    href: "/media-converters/mp4-webm",
    keywords: ["mp4", "webm", "web", "video"],
    popular: false,
  },
  {
    id: "webm-mp4",
    title: "WebM to MP4",
    description: "Convert WebM videos to MP4 format",
    category: "video",
    icon: Video,
    href: "/media-converters/webm-mp4",
    keywords: ["webm", "mp4", "web", "video"],
    popular: false,
  },
  {
    id: "mkv-mp4",
    title: "MKV to MP4",
    description: "Convert MKV videos to MP4 format",
    category: "video",
    icon: Video,
    href: "/media-converters/mkv-mp4",
    keywords: ["mkv", "mp4", "video", "convert"],
    popular: false,
  },
  {
    id: "mp4-mkv",
    title: "MP4 to MKV",
    description: "Convert MP4 videos to MKV format",
    category: "video",
    icon: Video,
    href: "/media-converters/mp4-mkv",
    keywords: ["mp4", "mkv", "video", "convert"],
    popular: false,
  },
  {
    id: "video-compress",
    title: "Compress Video",
    description: "Reduce video file size while maintaining quality",
    category: "video",
    icon: Film,
    href: "/media-converters/video-compress",
    keywords: ["compress", "video", "reduce", "size", "optimize"],
    popular: true,
  },
  {
    id: "extract-audio",
    title: "Extract Audio from Video",
    description: "Extract audio track from video files",
    category: "video",
    icon: Music,
    href: "/media-converters/extract-audio",
    keywords: ["extract", "audio", "video", "mp3", "sound"],
    popular: false,
  },

  // Audio Format Conversions
  {
    id: "mp3-wav",
    title: "MP3 to WAV",
    description: "Convert MP3 audio to WAV format",
    category: "audio",
    icon: Music,
    href: "/media-converters/mp3-wav",
    keywords: ["mp3", "wav", "audio", "convert", "lossless"],
    popular: false,
  },
  {
    id: "wav-mp3",
    title: "WAV to MP3",
    description: "Convert WAV audio to MP3 format",
    category: "audio",
    icon: Music,
    href: "/media-converters/wav-mp3",
    keywords: ["wav", "mp3", "audio", "convert", "compress"],
    popular: false,
  },
  {
    id: "mp3-flac",
    title: "MP3 to FLAC",
    description: "Convert MP3 audio to FLAC lossless format",
    category: "audio",
    icon: FileAudio,
    href: "/media-converters/mp3-flac",
    keywords: ["mp3", "flac", "audio", "lossless", "convert"],
    popular: false,
  },
  {
    id: "flac-mp3",
    title: "FLAC to MP3",
    description: "Convert FLAC lossless audio to MP3",
    category: "audio",
    icon: FileAudio,
    href: "/media-converters/flac-mp3",
    keywords: ["flac", "mp3", "audio", "lossless", "compress"],
    popular: false,
  },
  {
    id: "mp3-aac",
    title: "MP3 to AAC",
    description: "Convert MP3 audio to AAC format",
    category: "audio",
    icon: Music,
    href: "/media-converters/mp3-aac",
    keywords: ["mp3", "aac", "audio", "convert"],
    popular: false,
  },
  {
    id: "aac-mp3",
    title: "AAC to MP3",
    description: "Convert AAC audio to MP3 format",
    category: "audio",
    icon: Music,
    href: "/media-converters/aac-mp3",
    keywords: ["aac", "mp3", "audio", "convert"],
    popular: false,
  },
  {
    id: "ogg-mp3",
    title: "OGG to MP3",
    description: "Convert OGG audio files to MP3 format",
    category: "audio",
    icon: Music,
    href: "/media-converters/ogg-mp3",
    keywords: ["ogg", "mp3", "audio", "convert"],
    popular: false,
  },
  {
    id: "mp3-ogg",
    title: "MP3 to OGG",
    description: "Convert MP3 audio to OGG format",
    category: "audio",
    icon: Music,
    href: "/media-converters/mp3-ogg",
    keywords: ["mp3", "ogg", "audio", "convert"],
    popular: false,
  },

  // Image Conversions
  {
    id: "jpg-png",
    title: "JPG to PNG",
    description: "Convert JPG images to PNG format",
    category: "image",
    icon: ImageIcon,
    href: "/media-converters/jpg-png",
    keywords: ["jpg", "png", "image", "photo", "convert"],
    popular: true,
  },
  {
    id: "png-jpg",
    title: "PNG to JPG",
    description: "Convert PNG images to JPG format",
    category: "image",
    icon: ImageIcon,
    href: "/media-converters/png-jpg",
    keywords: ["png", "jpg", "image", "photo", "convert"],
    popular: true,
  },
  {
    id: "jpg-webp",
    title: "JPG to WebP",
    description: "Convert JPG images to WebP format",
    category: "image",
    icon: ImageIcon,
    href: "/media-converters/jpg-webp",
    keywords: ["jpg", "webp", "image", "web", "compress"],
    popular: false,
  },
  {
    id: "webp-jpg",
    title: "WebP to JPG",
    description: "Convert WebP images to JPG format",
    category: "image",
    icon: ImageIcon,
    href: "/media-converters/webp-jpg",
    keywords: ["webp", "jpg", "image", "convert"],
    popular: false,
  },
  {
    id: "png-webp",
    title: "PNG to WebP",
    description: "Convert PNG images to WebP format",
    category: "image",
    icon: ImageIcon,
    href: "/media-converters/png-webp",
    keywords: ["png", "webp", "image", "compress", "web"],
    popular: false,
  },
  {
    id: "webp-png",
    title: "WebP to PNG",
    description: "Convert WebP images to PNG format",
    category: "image",
    icon: ImageIcon,
    href: "/media-converters/webp-png",
    keywords: ["webp", "png", "image", "convert"],
    popular: false,
  },
  {
    id: "image-resize",
    title: "Resize Image",
    description: "Resize images to specific dimensions or percentages",
    category: "image",
    icon: ImageIcon,
    href: "/media-converters/image-resize",
    keywords: ["resize", "image", "scale", "dimensions"],
    popular: true,
  },
  {
    id: "image-compress",
    title: "Compress Image",
    description: "Reduce image file size while maintaining quality",
    category: "image",
    icon: ImageIcon,
    href: "/media-converters/image-compress",
    keywords: ["compress", "image", "optimize", "reduce", "size"],
    popular: true,
  },
]
