import { FileText, File, Archive, Code, FileJson, FileSpreadsheet } from "lucide-react"
import { ConverterMetadata } from "@/types/converter"

/**
 * File Converters Registry
 * All file/document conversion tools from FILE_CONVERSION_SERVICE_SPEC.md
 */
export const fileConverterTools: ConverterMetadata[] = [
  // Document Conversions - PDF
  {
    id: "pdf-word",
    title: "PDF to Word",
    description: "Convert PDF documents to Word format (DOCX)",
    category: "document",
    icon: FileText,
    href: "/file-converters/pdf-word",
    keywords: ["pdf", "word", "docx", "document", "edit"],
    popular: true,
  },
  {
    id: "word-pdf",
    title: "Word to PDF",
    description: "Convert Word documents (DOCX) to PDF format",
    category: "document",
    icon: FileText,
    href: "/file-converters/word-pdf",
    keywords: ["word", "pdf", "docx", "document", "convert"],
    popular: true,
  },
  {
    id: "pdf-powerpoint",
    title: "PDF to PowerPoint",
    description: "Convert PDF to PowerPoint presentation (PPTX)",
    category: "document",
    icon: FileText,
    href: "/file-converters/pdf-powerpoint",
    keywords: ["pdf", "powerpoint", "pptx", "presentation", "slides"],
    popular: false,
  },
  {
    id: "powerpoint-pdf",
    title: "PowerPoint to PDF",
    description: "Convert PowerPoint presentations to PDF format",
    category: "document",
    icon: FileText,
    href: "/file-converters/powerpoint-pdf",
    keywords: ["powerpoint", "pdf", "pptx", "presentation", "convert"],
    popular: true,
  },
  {
    id: "pdf-text",
    title: "PDF to Text",
    description: "Extract plain text from PDF documents",
    category: "document",
    icon: FileText,
    href: "/file-converters/pdf-text",
    keywords: ["pdf", "text", "txt", "extract", "plain text"],
    popular: true,
  },
  {
    id: "html-pdf",
    title: "HTML to PDF",
    description: "Convert HTML web pages to PDF documents",
    category: "document",
    icon: FileText,
    href: "/file-converters/html-pdf",
    keywords: ["html", "pdf", "web", "webpage", "convert"],
    popular: true,
  },
  {
    id: "markdown-pdf",
    title: "Markdown to PDF",
    description: "Convert Markdown files to PDF documents",
    category: "document",
    icon: FileText,
    href: "/file-converters/markdown-pdf",
    keywords: ["markdown", "pdf", "md", "convert"],
    popular: true,
  },
  {
    id: "markdown-html",
    title: "Markdown to HTML",
    description: "Convert Markdown to HTML format",
    category: "document",
    icon: Code,
    href: "/file-converters/markdown-html",
    keywords: ["markdown", "html", "md", "convert", "web"],
    popular: true,
  },

  // Spreadsheet Conversions
  {
    id: "excel-csv",
    title: "Excel to CSV",
    description: "Convert Excel spreadsheets (XLSX) to CSV format",
    category: "spreadsheet",
    icon: FileSpreadsheet,
    href: "/file-converters/excel-csv",
    keywords: ["excel", "csv", "xlsx", "spreadsheet", "data"],
    popular: true,
  },
  {
    id: "csv-excel",
    title: "CSV to Excel",
    description: "Convert CSV files to Excel spreadsheets (XLSX)",
    category: "spreadsheet",
    icon: FileSpreadsheet,
    href: "/file-converters/csv-excel",
    keywords: ["csv", "excel", "xlsx", "spreadsheet", "convert"],
    popular: true,
  },

  // Data Format Conversions
  {
    id: "json-yaml",
    title: "JSON to YAML",
    description: "Convert JSON data to YAML format",
    category: "data",
    icon: FileJson,
    href: "/file-converters/json-yaml",
    keywords: ["json", "yaml", "data", "convert", "config"],
    popular: true,
  },
  {
    id: "yaml-json",
    title: "YAML to JSON",
    description: "Convert YAML data to JSON format",
    category: "data",
    icon: FileJson,
    href: "/file-converters/yaml-json",
    keywords: ["yaml", "json", "data", "convert", "config"],
    popular: true,
  },
  {
    id: "json-xml",
    title: "JSON to XML",
    description: "Convert JSON data to XML format",
    category: "data",
    icon: Code,
    href: "/file-converters/json-xml",
    keywords: ["json", "xml", "data", "convert"],
    popular: false,
  },
  {
    id: "xml-json",
    title: "XML to JSON",
    description: "Convert XML data to JSON format",
    category: "data",
    icon: Code,
    href: "/file-converters/xml-json",
    keywords: ["xml", "json", "data", "convert"],
    popular: true,
  },
  {
    id: "csv-json",
    title: "CSV to JSON",
    description: "Convert CSV data to JSON format",
    category: "data",
    icon: FileJson,
    href: "/file-converters/csv-json",
    keywords: ["csv", "json", "data", "convert"],
    popular: true,
  },

  // Archive Conversions
  {
    id: "zip-extract",
    title: "Extract ZIP",
    description: "Extract files from ZIP archives",
    category: "archive",
    icon: Archive,
    href: "/file-converters/zip-extract",
    keywords: ["zip", "extract", "unzip", "archive", "decompress"],
    popular: true,
  },
  {
    id: "create-zip",
    title: "Create ZIP Archive",
    description: "Create ZIP archives from multiple files",
    category: "archive",
    icon: Archive,
    href: "/file-converters/create-zip",
    keywords: ["zip", "create", "archive", "compress", "multiple files"],
    popular: true,
  },

  // Encoding Conversions
  {
    id: "base64-encode",
    title: "Base64 Encode",
    description: "Encode files or text to Base64 format",
    category: "encoding",
    icon: Code,
    href: "/file-converters/base64-encode",
    keywords: ["base64", "encode", "encoding", "convert"],
    popular: true,
  },
  {
    id: "base64-decode",
    title: "Base64 Decode",
    description: "Decode Base64 encoded files or text",
    category: "encoding",
    icon: Code,
    href: "/file-converters/base64-decode",
    keywords: ["base64", "decode", "decoding", "convert"],
    popular: true,
  },
]
